[project]
name = "geo-attendance-system"
version = "0.1.0"
description = "Geo-based Attendance System"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "openpyxl>=3.1.5",
    "python-dotenv>=1.0.0",
]
